### ISSUE TITLE
Is it possible to open multiple sessions of the same left menu item?

### ISSUE THREAD

**Issue by hfirst** [layerok/react-router-tabs#1]
Great work!!!  Is there any way for a user to be able to launch a menu multiple times?  For example, user might click products, search for a product, edit it, etc.  Then they need to also go look something up in another product to finish their work on the 1st one.  Right now, any given menu item can only be opened once. 

1) Is it possible when they launch a route, for ex. /products, that it on the fly get converted to /products?sessionid=[guid] ?
2) However, then what about the state that is hardcoded in the AdminLayout? Any way to make that dynamic as tabs are opened and use the url they were assigned?

**Comment by hfirst** [comment]
I figured it out myself.  I added :id to all the root routes.  Then in my left nav menu, when they click products, I add on a guid to the end of the url and navigate to it and everything works!  I can now open a left menu any number of times and have multiple searches going on for the same entities.

Thank you so much for this. I hope it continues to work with future versions of react.

**Comment by layerok** [comment]
Exactly! The current implementation of useRouterTabs supports opening many tabs for the same route if it has a dynamic path parameter. 

Storing session id in the path parameter is even better than storing it in the query parameter because it doesn't require changing the current implementation of useRouterTabs.

In the beginning I was little bit puzzled by your issue. But the solution turned out to be pretty simple.
Good job.
